### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by rugk** [aerotoad/Thud#29]
It would be great to see this Android app on F-Droid!

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

BTW a release on F-Droid could also bring some (more) popularity (in case that is intended), as it will show up in the app (new apps are featured there).

**Comment by aerotoad** [comment]
I've been looking into it but it might be difficult since this is not a fully native app.
It was built on top of Capacitor using Angular, hence its build process is different than with fully native apps since you have to compile the angular project first.

When I have a little bit more time I'll study how feasible it is.

I'll mark this as help wanted in case someone has a better idea of how to do it.

**Comment by shuvashish76** [comment]
Currently available on izzy repo: https://apt.izzysoft.de/fdroid/index/apk/com.aerotoad.thud

A request for packaging has been opened here: https://gitlab.com/fdroid/rfp/-/issues/2077

**Comment by shuvashish76** [comment]
@aerotoad please double check if the the information I submitted are correct or not.
Also let me know if you wanna add your Email, WebSite, Donation link etc...
IMO we should add donation link there. Please share your PayPal ID link.

**Comment by IzzySoft** [comment]
Issuebot already complained about missing Fastlane, so I took the freedom to provide via a PR what's in use at my repo. As for donation links, may I rather suggest to use [Github's `FUNDING.yml`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository), which is fully supported by F-Droid meanwhile? That way @aerotoad can maintain these details here in the repo, and would not need MRs at F-Droid should adjustments be needed.

PS: if until your app was included at F-Droid you want to link to your app's presence in my repo (e.g. from the Readme), you can find a proper [badge here](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) :smiley:

**Comment by shuvashish76** [comment]
@aerotoad Fastlane is just part of the F-Droid inclusion process. Please keep this issue open...

**Comment by aerotoad** [comment]
@shuvashish76 That is true, reopening.

**Comment by aerotoad** [comment]
I've been quite busy with my job these past two weeks and couldn't keep track of this properly.
@IzzySoft @shuvashish76 Is there any other information or configuration file missing that is required to complete the process?

**Comment by IzzySoft** [comment]
Thanks to your merging my Fastlane PR, as far as I can see we might only need a fresh tag covering that. If Fastlane was the only change at that time (i.e. no code changes, especially no changes to versionCode/versionName), we could simply start with that explicit commit for now (and set the metadata up to switch to tags with the next release). Just let us know, we can then trigger a rescan by our bot.

**Comment by aerotoad** [comment]
There has been another merge of a PR fixing some typos and texts, other than that, no major funcionality changes or improvements.
I want to finish at least with the OPML import/export functionality before making another release.

Would it be possible to trigger the bot without creating a new release under this circumstances?

**Comment by IzzySoft** [comment]
Sure, I've just done that. And yes, even the merge request (to establish your app in the F-Droid catalog) can be done before the new tag (as mentioned, we could just specify the commit hash of when Fastlane was added). If that shows all's fine, you can still decide whether to wait for the tag or not.

**Comment by mariobrostech** [comment]
Is there any progress on Thud making its way to the mainline F-Droid repo?

**Comment by shuvashish76** [comment]
Live on F-Droid: https://f-droid.org/en/packages/com.aerotoad.thud/ 🎉

**Comment by aerotoad** [comment]
Sice everything seems to be ready and there are no further requests on this topic I'll be closing the issue as resolved.

**Comment by IzzySoft** [comment]
@aerotoad one last question: with your app now being listed at F-Droid (congrats!), do you want me to keep it in my repo as well? Usually I remove apps from my repo at this stage, giving a proper overlap (10..14 days) unless explicitly requested otherwise.
