### ISSUE TITLE
Download badges on README page

### ISSUE THREAD

**Issue by shuvashish76** [aerotoad/Thud#32]
`[![IzzyOnDroid](https://img.shields.io/endpoint?url=https://apt.izzysoft.de/fdroid/api/v1/shield/com.aerotoad.thud)](https://apt.izzysoft.de/fdroid/index/apk/com.aerotoad.thud)`

Downloads

`[<img alt="Get it on Google Play" height="80" src="https://play.google.com/intl/en_us/badges/images/generic/en_badge_web_generic.png">](https://play.google.com/store/apps/details?id=com.aerotoad.thud)`
`[<img alt="Get it on IzzyOnDroid" height="80" src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png">](https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager)`

refer: https://gitlab.com/IzzyOnDroid/repo/blob/master/README.md#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it

**Comment by aerotoad** [comment]
Thanks! I'll create a PR with the Google Play link, I think it's better to wait and see if it goes through on the F-Droid main repo since that's the one people usually use instead of the izzy on droid.

**Comment by aerotoad** [comment]
Closing this for now, feel free to open another one if F-Droid accepts the app, I'll try to keep an eye there as well.

**Comment by shuvashish76** [comment]
For future reference : https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md
