### ISSUE TITLE
Open in default browser rather than google chrome

### ISSUE THREAD

**Issue by scotty-p20** [aerotoad/Thud#50]
I have firefox focus as my default browser on mobile because I'm trying to avoid google, downloaded Thud as an alternative to the google newsfeed itself.

I would love if I could just set my own default browser as the browser articles open into.

**Comment by aerotoad** [comment]
@scotty-p20 This is actually a feature that I wanted to implement for some time. Would it fit your needs if I add an option to disable the in-app browser so links and articles are opened on whatever browser is set as default on the phone?

**Comment by scotty-p20** [comment]
Yes that would be great!

**Comment by scotty-p20** [comment]
Mostly joking, but if you could then have the podcasts play with in the
app.... whooo that would be fantastic, totally a dream though I imagine,
but I could get rid of Google podcasts as well.

**Comment by aerotoad** [comment]
What podcasts are you adding to your collections? I intended Thud. to work more or less the same as the original Pulse news, but if I find an easy way to add an in-app player I can look into it. It all boils down to the level of standarization for podcasts (that I'm not very familiar with)

**Comment by aerotoad** [comment]
@scotty-p20 The feature for opening the articles in the phone's browser has been shipped! 
You can download the latest version of the app in the release section of the repo or (if you used google play) wait for google play to approve the update.

**Comment by scotty-p20** [comment]
Thanks so much! This has been great! F droid hasn't been updated yet, so
uninstalled, then downloaded again from the play store and just got the
collections set back up.
